version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Node 20 compatible
    container_name: mcp-server
    restart: unless-stopped
    environment:
      - JWT_SECRET
      - DB_PASSWORD
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/healthz || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Uncomment for dev hot-reload
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    # command: ["npm", "run", "start"]
  # Add additional services (e.g., redis) as needed
# networks:
#   default:
#     driver: bridge
