version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Uncomment for dev hot-reload
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    # command: ["npm", "run", "start"]
  # Add additional services (e.g., redis) as needed
# networks:
#   default:
#     driver: bridge
